COLLEGE_NAME_LIST = [
    "I do not have a college degree,"
    "St. Stephen's College",
    "Women Christian College",
    "MCM DAV College for Women",
    "Symbiosis Society's College of Arts & Commerce",
    "Nizam's College",
    "K J Somaiya College of Arts & Commerce",
    "Rajiv Gandhi National University of Law (RGNUL)",
    "Tamilnadu Dr. Ambedkar Law University",
    "National University of Advanced Legal Studies",
    "Department of Media Studies,Christ University",
    "VeerMata Jijabai Technological Institute(VJTI, Mumbai)",
    "Mithibai Arts Chauhan Institute",
    "University College-Kurukshetra",
    "St.Joseph's College",
    "Kamala Nehru College for Women",
    "Institute of Technology, Banaras Hindu University (IT, BHU)",
    "Jesus & Mary College (JMC)",
    "Nowrosjee Wadia College",
    "Department of Fine Arts, Kurukshetra University",
    "St. John's Medical College",
    "Jyothi Nivas College",
    "Delhi Technological University",
    "Government Law College",
    "Maulana Azad College",
    "National Law Institute University",
    "Symbiosis Society's College of Arts & Commerce",
    "Guru Nanak Khalsa College of Arts,Science & Commerce",
    "Delhi College of Arts & Commerce",
    "Hindu College",
    "Seth Gordhandas Sunderdas Medical College",
    "Ethiraj College for Women",
    "Bharti Vidyapeeth's Kala Mavidyalaya College of Fine Arts",
    "The Oxford College of Science",
    "Elphinstone College",
    "Sophia College for Women",
    "Goenka College of Commerce and Business Administration",
    "Loyola Academy Degree & P G College",
    "Nilratan Sircar Medical College",
    "Stella Maris College",
    "Loyola Academy Degree & P G College",
    "Osmania University College for Women",
    "Ramniranjan Jhunjhunwala College",
    "Indian Institute of Technology(IIT)",
    "Faculty of Law,Osmania University",
    "Indian Institute of Technology",
    "All India Institute of Medical Sciences(AIIMS)",
    "Northern India Institute of Fashion Technology (NIIFT)",
    "College of Art",
    "University College of Medical Sciences & GTB Hospital",
    "Presidency College",
    "D.G Vaishnav College",
    "Army Institute of Law (AIL)",
    "Vellore Institute of Technology(VIT)",
    "National Institute of Technology",
    "Amrita Institute of Medical Sciences & Research Centre",
    "Department of Business Administration, SRM University",
    "J D Birla Institute",
    "Faculty of Visual Arts - Banaras Hindu University",
    "Mount Carmel College",
    "Rani Birla Girls College",
    "St. Andrew's College of Arts,Science and Commerce",
    "International Institute of Information Technology (IIIT-H)",
    "St. Andrew's College of Arts,Science and Commerce",
    "Jesus & Mary College (JMC)",
    "Maharani Lakshmi Ammanni College for Women (MLACW)",
    "PSG College of Technology",
    "Osmania Medical College",
    "J.D. Birla Institute",
    "Netaji Subhash Institute Of Technology",
    "University College of Law, Bangalore University",
    "Indraprastha College for Women",
    "Sri Venkateswara College",
    "Sri Ram College of Commerce(SRCC)",
    "Shri Narsee Monjee College of Commerce and Economics",
    "Symbiosis Institute of Media and Communication - Under Graduate",
    "Christ College",
    "The W.B. National University of Juridical Sciences(NUJS)",
    "MOP Vaishnav College for Women",
    "Sir J J School of Arts",
    "C. C. Sheth College of Commerce",
    "Faculty of Law , ICFAI University (ICFAI Law School)",
    "Cotton College",
    "Ethiraj College",
    "Lady Shriram College for Women (LSR)",
    "Fergusson College",
    "Seshadripuram College",
    "Madras Christian College",
    "Hansraj College",
    "Ramnarain Ruia College",
    "National College, Basavangudi",
    "S. S. & L. S. Patkar College of Arts & Science & V. P. Varde College of Commerce & Economics",
    "Amity School Of Communication",
    "Jai Hind College",
    "S.G.T.B. Khalsa College",
    "Maharani Laxmi Ammanni College For Women",
    "Lady Shriram College for Women (LSR)",
    "Faculty of Law,Jamia Millia Islmia",
    "Mithibai College",
    "Medical College & Hospital",
    "Faculty of Law, Aligarh Muslim University",
    "Madras Medical College (Chennai Medical College)",
    "Madras Christian College",
    "H.L.College of commerce",
    "Lady Hardinge Medical College(LHMC)",
    "Department of Fine Arts, Aligarh Muslim University",
    "H.K.Arts College",
    "Bhavan's New Science College",
    "Maharani Lakshmi Ammanni College for Women (MLACW)",
    "Birla Institute of Technology, Mesra(BITS, Mesra)",
    "Visva-Bharati, Kala Bhavan (Institute of Fine Arts)",
    "Madras Christian College(MCC)",
    "Pearl Academy",
    "JNTU College of Engineering",
    "Kasturba Medical College(KMC)",
    "National Law Institute University(NLIU)",
    "Kishinchand Chellaram College Art Commerce & Science",
    "Presidency College",
    "S.R.M. Engineering College",
    "Stanley Medical College (SMC)",
    "Hindu College",
    "Wilson College",
    "St. Xavier College",
    "Loyola College",
    "Madras Christian College(MCC)",
    "Faculty of Law, Banaras Hindu University",
    "Christian Medical College, Vellore (CMC, Vellore)",
    "St. Francis College for Women",
    "Kristu Jayanti College",
    "Indian institute of Management and Commerce",
    "Delhi College of Arts & Commerce (DCAC)",
    "Women's Christian College",
    "School of Legal Studies, Cochin University of Science and Technology",
    "I.L.S. Law College",
    "St. Joseph's College",
    "Gargi College",
    "Manipal Institute of Communications",
    "Sri Guru Gobind Singh College of Commerce",
    "Kamala Nehru College for Women",
    "Symbiosis Society's Law College",
    "Amity Law School",
    "National College - Jayanagar",
    "Netaji Subhash Chandra Bose Degree College",
    "St. Xavier's College",
    "Jyoti Nivas College",
    "Asutosh College",
    "National P.G. College",
    "Thapar Institute of Engineering and Technology",
    "Kishinchand Chellaram (K C) College of Arts, Science and Commerce",
    "Jyothi Nivas College",
    "Sacred Heart College",
    "Christ College",
    "Armed Forces Medical College(AFMC)",
    "M S Ramaiah Institute of Technology",
    "Indian Institute of Information Technology (IIIT-A)",
    "Sri Ramachandra Medical College & Research Institute",
    "The Oxford College of Business Management",
    "Government College of Engineering (COEP)",
    "St. Mira's College for Girls",
    "K.P.B. Hinduja College of Commerce and Economics",
    "International College for Girls",
    "National Law School of India University(NLSIU)",
    "Mithibai College of Arts",
    "Faculty of Management, Banasthali University",
    "Institute of Management Studies",
    "Christian Medical College(CMC, Ludhiana)",
    "Institute of Medical Sciences",
    "Gujarat National Law University",
    "JIPMER",
    "National Institute of Fashion Technology (NIFT)",
    "Lucknow Christian Degree College",
    "Grant Medical College",
    "Campus Law Centre, University of Delhi",
    "Faculty of Law, University of Kolkata",
    "Maulana Azad Medical College(MAMC)",
    "Bangalore Medical College(BMC)",
    "Indraprastha College for women",
    "Mount Carmel College",
    "R.A. Podar College of Commerce and Economics",
    "M.S. Ramaiah College of Arts, Science and Commerce",
    "M S Ramaiah Medical College",
    "Deen Dayal Upadhyay College",
    "Christ University",
    "R. G. Shah Science College",
    "National Academy of Legal Studies and Research University (NALSAR)",
    "MCM DAV College for Women - Sec 36 A",
    "Lady Shri Ram College for Women",
    "Maharaja Agrasen College (MAC)",
    "Faculty of Music & Fine Arts - University of Delhi",
    "Institute of Management Studies (IMS)",
    "Xavier Institute of Computer Application",
    "Women's Christian College",
    "Bangalore Institute of Legal Studies",
    "L S Raheja School of Art",
    "Kamala Nehru College",
    "King George Medical College - Chhatrapati Shahuji Maharaj Medical University",
    "Vivekananda First Grade College of Arts, Science & Commerce",
    "Indian Institute of Technology(IIT)",
    "Miranda House",
    "GGDSD College",
    "M P Arts & M H Commerce College for Women, Ahmedabad",
    "Sacred Heart College",
    "The Institute of Post Graduate Medical Education & Research (IPGMER)",
    "Guru Nanak College",
    "Amity School of Fashion Technology",
    "Amity International Business School",
    "Amity University",
    "Birla Institute of Technology and Sciences(BITS, Pilani)",
    "B J Medical College",
    "M E S College of Arts, Science & Commerce",
    "St.Xavier's College",
    "University College of Fine Arts, University of Mysore",
    "Vinayak Ganesh Vaze College of Arts, Science and Commerce",
    "M.S.Ramaiah Junior and Degree College",
    "DAV College",
    "Loyola College",
    "Shaheed Bhagat Singh College",
    "Ramjas College",
    "Sri Ram College of Commerce(SRCC)",
    "St. Xavier's College",
    "H.A.College of commerce",
    "Department of Computer Applications, SRM University",
    "Vivekananda College",
    "Shri Bhagawan Mahaveer Jain College",
    "Christ College of Law"
]
