COMPANY_NAME_LIST = [
    "Big Basket (Online Retail)",
    "Urban Ladder (Online Retail)",
    "PepperFry (Online Retail)",
    "Ziffi (Online Retail)",
    "UrbanClap (On-Demand Aggregator)",
    "Zimmber (On-Demand Aggregator)",
    "HouseJoy (On-Demand Aggregator)",
    "Care24 (On-Demand Aggregator)",
    "Portea (On-Demand Aggregator)",
    "HCAH (On-Demand Aggregator)",
    "Vedantu (On-Demand Aggregator)",
    "CueMath (On-Demand Aggregator)",
    "Aditya Birla Fashion/Madhura Lifestyle (Modern Retail)",
    "Arvind Retail (Modern Retail)",
    "Big Bazaar (Modern Retail)",
    "Vmart (Modern Retail)",
    "Cantabil (Modern Retail)",
    "Liberty (Modern Retail)",
    "Tristar Retail (Modern Retail)",
    "V2 Retail (Modern Retail)",
    "FabIndia (Modern Retail)",
    "Reliance Retail (Modern Retail)",
    "Spencer's (Modern Retail)",
    "Hypercity (Modern Retail)",
    "Westside (Trent Retail) (Modern Retail)",
    "Raymond (Modern Retail)",
    "Walmart (Modern Retail)",
    "Future Group (Modern Retail)",
    "Shopper's Stop (Modern Retail)",
    "Benetton (Modern Retail)",
    "Addidas (Modern Retail)",
    "Nike (Modern Retail)",
    "Puma (Modern Retail)",
    "Levis (Modern Retail)",
    "Lenskart (Modern Retail)",
    "UrbanLadder (Modern Retail)",
    "Caratlane (Modern Retail)",
    "JoyAlukkas (Modern Retail)",
    "Kalyan Jewellers (Modern Retail)",
    "Tanishq (Modern Retail)",
    "Arvind (Modern Manufacturing)",
    "Welspun (Modern Manufacturing)",
    "P&G (Modern Manufacturing)",
    "HUL (Modern Manufacturing)",
    "Runnr (Logistics (Delivery))",
    "Delhivery (Logistics (Delivery))",
    "BlueDart (Logistics (Delivery))",
    "Swiggy (Logistics (Delivery))",
    "Rivigo (Logistics (Delivery))",
    "BlackBuck (Logistics (Delivery))",
    "Zomato (Logistics (Delivery))",
    "Ecom Express (Logistics (Delivery))",
    "Xpress Bees (Logistics (Delivery))",
    "Peppertap/NuvoEx (Logistics (Delivery))",
    "DTDC (Logistics (Delivery))",
    "First Flight (Logistics (Delivery))",
    "Shadowfax (Logistics (Delivery))",
    "Zopper (Logistics (Delivery))",
    "Meru Cabs (Logistics (Commute))",
    "Uber (Logistics (Commute))",
    "Ola (Logistics (Commute))",
    "Jugnoo (Logistics (Commute))",
    "MegaCabs (Logistics (Commute))",
    "Savaari (Logistics (Commute))",
    "Tab Cab (Logistics (Commute))",
    "Genpact (IT & BPO)",
    "IHG (Hotels)",
    "LemonTree (Hotels)",
    "Treebo (Hotels)",
    "Oyo (Hotels)",
    "Spree (Hotels)",
    "Vista (Hotels)",
    "Wyndham (Hotels)",
    "Best Western (Hotels)",
    "Accor (Hotels)",
    "Taj (Hotels)",
    "Oberoi (Hotels)",
    "Starwood (Hotels)",
    "Carlson Reizdor (Hotels)",
    "Hyatt (Hotels)",
    "Choice (Hotels)",
    "Hilton (Hotels)",
    "Four Seasons (Hotels)",
    "JLL (Facility Management)",
    "G4S (Facility Management)",
    "SIS (Facility Management)",
    "G7 Securitas (Facility Management)",
    "DSS Security (Facility Management)",
    "Tenon Services (Facility Management)",
    "Avon (Facility Management)",
    "BVG (Facility Management)",
    "ISS Security (Facility Management)",
    "TOPS Security (Facility Management)",
    "Securitas (Facility Management)",
    "Europa (Facility Management)",
    "Chaayos (F & B Retail)",
    "Chai Point (F & B Retail)",
    "Tea Halt (F & B Retail)",
    "Box8 (F & B Retail)",
    "CCD (F & B Retail)",
    "Costa (F & B Retail)",
    "Faasos (F & B Retail)",
    "Impressario Foods (F & B Retail)",
    "Haldiram (F & B Retail)",
    "Goli Wada Pav (F & B Retail)",
    "Mongines (F & B Retail)",
    "Nirula's (F & B Retail)",
    "Dominoes (F & B Retail)",
    "Pizza Hut (F & B Retail)",
    "BBQ Nation (F & B Retail)",
    "Starbucks (F & B Retail)",
    "Subway (F & B Retail)",
    "Sbarro (F & B Retail)",
    "Papa John's  (F & B Retail)",
    "McDonald (F & B Retail)",
    "KFC (F & B Retail)",
    "Dunkin Donut's (F & B Retail)",
    "Burger King (F & B Retail)",
    "Chilli's (F & B Retail)",
    "Baskin Robins (F & B Retail)",
    "Creambell (F & B Retail)",
    "Bikanerwala (F & B Retail)",
    "Mainland China (F & B Retail)",
    "Kobe (F & B Retail)",
    "Nando (F & B Retail)",
    "Yellow Chilli (F & B Retail)",
    "Bharat Electronics Limited",
    "Bharat Heavy Electricals Limited",
    "Bharat Petroleum Corporation Limited",
    "Bharti Airtel Limited",
    "Bharti AXA Investment Managers  Private Limited",
    "Bharti AXA Life Insurance Company Limited",
    "Bharti Infratel Limited",
    "Bhatia Hospital",
    "Bhilosa Industries Private Limited",
    "Billets Elektro Werke Limited",
    "Binani Cement Limited",
    "Binani Industries Limited",
    "Biochem Pharmaceutical Industries Limited",
    "Biostadt India Limited",
    "Birla Sun Life Asset Management Company Limited",
    "Birla Sun Life Insurance Company Limited",
    "BLA Industries Private Limited",
    "Blow Plast Limited",
    "BLR Logistiks India Limited",
    "Blue Chip Corporate Investment Centre Limited",
    "Blue Cross Laboratories Limited",
    "Blue Dart Express Limited",
    "Blue Star Infotech Limited",
    "Blue Star Limited",
    "BMS Industries Limited",
    "BNP Paribas India",
    "BNP Paribas India Solutions  Private Limited",
    "Bombay Hospital & Medical Research Centre",
    "Bombay Intelligence Security India Limited",
    "Bombay Stock Exchange Limited",
    "Borosil Glass Works Limited",
    "Bosch Limited",
    "BPB India Gypsum",
    "Brabourne Enterprises Limited",
    "Breach Candy Hospital Trust",
    "Bright AutoPlast Private Limited",
    "Brinks Arya India  Private Limited",
    "Bristlecone India Limited",
    "Bristol-Myres Squibb India Private Limited",
    "Britannia Industries Limited",
    "Bureau Veritas Industrial Services India Private Limited",
    "Business India Publications Limited",
    "BYL Nair Charitable Hospital",
    "Cable Corporation of India Limited",
    "Cadbury India Limited",
    "Cadila Healthcare Limited",
    "Cairn India Limited",
    "Call 2 Connect India Private Limited",
    "Calyon Bank",
    "Cambata Aviation  Private Limited",
    "Camlin Limited",
    "Cantronics Office Equipments Private Limited",
    "Capgemini Consulting India  Private Limited",
    "Capita India  Private Limited",
    "Capricorn Logistics Private Limited",
    "Caprihans India Limited",
    "Carol Info Services Limited",
    "Castrol India Limited",
    "CC Chokshi and Company",
    "Ceat Limited",
    "Celebi NAS Airport Services India Private Limited",
    "Celetronix India Private Limited",
    "Cello International  Private Limited",
    "Centaur Pharmaceuticals  Private Limited",
    "Central Investigation and Security Services Limited",
    "Centre for Development of Advanced Computing",
    "Centrum Capital Limited",
    "Century Rayon",
    "Century Textiles & Industries Limited",
    "CFC India Services  Private Limited",
    "Chandan Steel Limited",
    "Charak Pharmaceuticals  Private Limited",
    "Chawla Brothers Limited",
    "Chevron Metal Products  Private Limited",
    "Cinemax India Limited",
    "Cipla Limited",
    "Citigroup Global Markets India Private Limited",
    "Clariant India Limited",
    "Classic Diamonds India Limited",
    "Classic Stripes Private Limited",
    "CMC Limited",
    "CMI FPE Limited",
    "CMS Computers Limited",
    "Coal India Limited",
    "Colaba Central Co-operative Consumers Wholesale & Retail Stores Limited",
    "Colgate-Palmolive (India) Limited",
    "Colgate-Palmolive India Limited",
    "Colorplus Fashions Limited",
    "Comart Lithographers Limited",
    "Comfort Inn Heritage",
    "Concept Communication Limited",
    "Concept Pharmaceuticals Limited",
    "Container Corporation Of India Limited",
    "Control Print Limited",
    "Coral Laboratories Limited",
    "Cox & Kings Limited",
    "Creative Garments  Private Limited",
    "Credit Analysis & Research Limited",
    "Crest Animation Studios Limited",
    "CRISIL Limited",
    "Crompton Greaves Limited",
    "CRP Technologies India Private Limited",
    "Cummins India Limited",
    "Dabur India Limited",
    "Datamatics Global Services Limited",
    "Datamatics Limited",
    "Datapro Consultancy Services Private Limited",
    "Dawn Mills Company Limited",
    "DBS Bank Limited",
    "DC Polyester Limited",
    "DCW Limited",
    "Dee Greaves Limited",
    "Deep Water Services India Limited",
    "Della Tecnica Interior Design And Project Management Private Limited",
    "Deloitte Haskins & Sells",
    "Deloitte Touche Tohmatsu India  Private Limited",
    "Delta Services India Private Limited",
    "Det Norske Veritas",
    "Dhanasingh Synthetics Private Limited",
    "DHL Express India  Private Limited",
    "Dicitex Decor Exports",
    "Dicitex Furnishings Limited",
    "Dicitex Industries  Private Limited",
    "Diebold Systems Private Limited",
    "Digicable Network India Private Limited",
    "Diligent Media Corporation Limited",
    "Dimexon Diamonds Limited",
    "Dinurje Jewellery Private Limited",
    "Dlf Limited",
    "Dodsal Corporation  Private Limited",
    "Dodsal Enterprises Private Limited",
    "Domex e-Data Private Limited",
    "Donear Industries Limited",
    "Dow AgroSciences India Private Limited",
    "Dr Balabhai Nanavati Hospital",
    "Dr.Reddy'S Laboratories Limited",
    "DSP Merrill Lynch Limited",
    "Dwarikesh Sugar Industries Limited",
    "DWD Pharmaceuticals Limited",
    "East West Freight Carriers Private Limited",
    "eBay India  Private Limited",
    "Echjay Industries Private Limited",
    "ECI Telecom India  Private Limited",
    "E-City Entertainment India  Private Limited",
    "eClerx Services Limited",
    "Edelweiss Capital Limited",
    "Edelweiss Securities Limited",
    "Egana India Private Limited",
    "Eicher Motors Limited",
    "Elbee Express  Private Limited",
    "Elbee Services Limited",
    "Elder Instruments Private Limited",
    "Elder Pharmaceuticals Limited",
    "Electropneumatics & Hydraulics India  Private Limited",
    "Emami Limited-$",
    "Embio Limited",
    "Emerald Realtors Private Limited",
    "Emergent Genetics India Private Limited",
    "Emirates Airlines",
    "Empire Industries Limited",
    "Enam Securities Private Limited",
    "Endurance Systems India  Private Limited",
    "Enercon India Limited",
    "Engineering & Designs Tecnimont I C B  Private Limited",
    "Entertainment Network India Limited",
    "Esjay International Private Limited",
    "Eskay K'N'It India Limited",
    "Essar Oil Limited",
    "Essar Power Limited",
    "Essar Shipping Ports & Logistics Limited",
    "Essar Steel Limited",
    "Essel Corporate Resources Private Limited",
    "Essel Propack Limited",
    "Eureka Forbes Limited",
    "Everest Kanto Cylinder Limited",
    "Excel Apparels Exports Private Limited",
    "Excel Crop Care Limited",
    "Excel Garments Manufacturing Private Limited",
    "Excel Industries Limited",
    "Exel India  Private Limited",
    "Export Credit Guarantee Corporation of India Limited",
    "Export-Import Bank of India",
    "Expressindia Com Private Limited",
    "Faze Three Limited",
    "FDC Limited",
    "Federal Express Corporation",
    "Financial Information Network & Operations Limited",
    "Financial Technologies India Limited",
    "Fine Jewellery Manufacturing Limited",
    "Fine Organics Industries Private Limited",
    "First Advantage Private Limited",
    "First Data India Private Limited",
    "First Flight Couriers Limited",
    "First Offshoring Technologies  Private Limited",
    "Flamingo Pharmaceuticals Limited",
    "Fly Jac Forwarders",
    "Flyjac Logistics  Private Limited",
    "Flyking Courier Services Private Limited",
    "Forbes & Company Limited",
    "Forbes Campbell Knitwear",
    "Fort Point Automotive Private Limited",
    "Fortis Hospitals Limited",
    "Fouress Engineering India Limited",
    "Franco-Indian Pharmaceuticals Private Limited",
    "Franklin Templeton Asset Management India Private Limited",
    "Frigorifico Allana Limited",
    "FRR Forex Private Limited",
    "Fun Multiplex Private Limited",
    "Future Generali India Insurance Company Limited",
    "Gail (India) Limited",
    "Galaxy Office Automation Private Limited",
    "Galentic Pharma India Private Limited",
    "Galpha Laboratories Limited",
    "Gammon India Limited",
    "Ganesh Benzoplast Limited",
    "Gannon Dunkerley & Company Limited",
    "Garware Chemicals Limited",
    "Garware Polyester Limited",
    "Geil Projects & Services India Limited",
    "Geldhof  Private Limited",
    "Gemini Equipment and Rentals Private Limited",
    "General Insurance Corporation of India",
    "Geochem Laboratories Private Limited",
    "Geometric Limited",
    "German Remedies Limited",
    "GIC Housing Finance Limited",
    "Gili India Limited",
    "Gillette India Limited",
    "Gini & Jony Limited",
    "Gini Silk Mills Limited",
    "Gitanjali Gems Limited",
    "Glaxosmithkline Consumer Healthcare Limited",
    "GlaxoSmithkline Pharmaceuticals Limited",
    "Glenmark Pharmaceuticals Limited",
    "GlobeOp Financial Services India Private Limited",
    "Globus Stores Private Limited",
    "Glodyne Technoserve Limited",
    "GMM Pfaudler Limited",
    "Godavari Biorefineries Limited",
    "Godrej & Boyce Manufacturing Company Limited",
    "Godrej Agrovet Limited",
    "Godrej Appliances Limited",
    "Godrej Consumer Products Limited",
    "Godrej Household Products Limited",
    "Godrej Industries Limited",
    "Godrej Infotech Limited",
    "Godrej Lifespace",
    "Gold Shield Services Private Limited",
    "Gold Star Diamond  Private Limited",
    "Golden Chemicals Private Limited",
    "Golden Tobacco Limited",
    "Goldiam International Limited",
    "Goldstar Jewellery Limited",
    "Govind Rubber Limited",
    "Graco Inc Usa",
    "Grand Hyatt Mumbai",
    "Grasim Industries Limited",
    "Grauer & Weil India Limited",
    "Graviss Holdings Private Limited",
    "Great Offshore Limited",
    "Greaves Cotton Limited",
    "Grindwell Norton Limited",
    "GSL India Limited",
    "GT Hospital",
    "GTL Limited",
    "Gufic Biosciences Limited",
    "Gufic Limited",
    "Gujarat Reclaim And Rubber Products Limited",
    "Gujarat Sidhee Cement Limited",
    "Gujarat State Fertilizers Company Limited",
    "Gulf Oil Corporation Limited",
    "H&R Johnson India",
    "Haldyn Glass Gujarat Limited",
    "Haldyn Glass Limited",
    "Hapag-Lloyd India Private Limited",
    "Hardcastle Restaurants  Private Limited",
    "Hari Krishna Exports",
    "Harinagar Sugar Mills Limited",
    "Hariyana Ship Breakers Limited",
    "Hathway Cable & Datacom Limited",
    "Havells India Limited",
    "Hawkins Cookers Limited",
    "Hcl Technologies Limited",
    "HDFC Asset Management Company Limited",
    "Hdfc Bank Limited",
    "HDFC Investments Limited",
    "HDFC Securities Limited",
    "HDFC Standard Life Insurance Company Limited",
    "HDFC-Ergo General Insurance Company Limited",
    "Heinz India  Private Limited",
    "Hemlines Textile Exports Private Limited",
    "Hero Motocorp Limited",
    "Hindalco Industries Limited",
    "Hinduja Ventures Limited",
    "Hindustan Coca-Cola Marketing Company  Private Limited",
    "Hindustan Composites Limited",
    "Hindustan Construction Company Limited",
    "Hindustan Dorr-Oliver Limited",
    "Hindustan Organic Chemicals Limited",
    "Hindustan Pencils  Private Limited",
    "Hindustan Petroleum Corporation Limited",
    "Hindustan Unilever Limited",
    "Hindustan Zinc Limited",
    "Hiranandani Constructions  Private Limited",
    "Hiranandani Developers  Private Limited",
    "Hirco Developments Private Limited",
    "Home Loans Service  Private Limited",
    "Hotel Leela Venture Limited",
    "Housing Development & Infrastructure Limited",
    "Housing Development Finance Corp.Limited",
    "HSBC InvestDirect Securities India Limited",
    "Hutchison 3 Global Services  Private Limited",
    "Hydrogas India Private Limited",
    "HyperCity Retail India Limited",
    "IBP Company Limited",
    "Icici Bank Limited",
    "ICICI Home Finance Company Limited",
    "ICICI Lombard General Insurance Company Limited",
    "ICICI Prudential Asset Management Company Limited",
    "ICICI Prudential Life Insurance Company Limited",
    "IDBI Capital Market Services Limited",
    "IDBI Federal Life Insurance Company Limited",
    "IDEA Cellular Limited",
    "Ideal Road Builders  Private Limited",
    "IL&FS Education & Technology Services Limited",
    "IL&FS Investment Managers Limited",
    "IMP Power Limited",
    "IMRB International",
    "In2cable India Limited",
    "Indchemie Health Specialities Private Limited",
    "India Foils Limited",
    "India Infoline Limited",
    "India Infoline Securities  Private Limited",
    "India Infoline.com Distribution Company Limited",
    "India Steel Works Limited",
    "Indiabulls Housing Finance Limited",
    "IndiaFirst Life Insurance Company Limited",
    "IndiaIdeas.com Limited",
    "Indian Institute of Technology, Bombay",
    "Indian Naval Hospital Ship Asvini",
    "Indian Oil Corporation Limited",
    "Indian Rare Earths Limited",
    "Indiana Conveyors Private Limited",
    "IndiaNivesh Securities  Private Limited",
    "Indo Count Industries Limited",
    "Indoco Remedies Limited",
    "Indofil Chemicals Company",
    "Indofil Organic Industries Limited",
    "Indusind Bank Limited",
    "Indusind Information Technology Limited",
    "IndusInd Media & Communications Limited",
    "Industrial Oxygen Company Limited",
    "Infomedia 18 Limited",
    "Infosys Limited",
    "Infrasoft Technologies Limited",
    "Infrastructure Leasing & Financial Services Limited",
    "Ingram Micro India  Private Limited",
    "Inland Road Transport Private Limited",
    "Inox Air Products Limited",
    "Inox Leisure Limited",
    "Insight Business Machines Private Limited",
    "Integrated Logistics India Services Private Limited",
    "Integrated Property Management Services Limited",
    "Integreon Managed Solutions India Private Limited",
    "Intelenet Global Services  Private Limited",
    "Inter Jewels India Private Limited",
    "Interglobe Aviation Limited",
    "International Distillers India Limited",
    "International Gold Company Limited",
    "Ion Exchange India Limited",
    "IOT Infrastructure & Energy Services Limited",
    "Ipca Laboratories Limited",
    "Iron Mountain India Private Limited",
    "iSmart BPO Services  Private Limited",
    "Ispat Industries Limited",
    "Itc Limited",
    "ITD Cementation India Limited",
    "Ivory Properties & Hotels Private Limited",
    "J Walter Thompson Company Limited",
    "Jacobs Engineering India  Private Limited",
    "Jai Corp Limited",
    "Janmabhoomi Group of Newspapers",
    "Jaslok Hospital & Research Center",
    "Jayabharat Credit Limited",
    "JB & Brothers",
    "JB Boda & Brothers Private Limited",
    "JB Boda & Company Private Limited",
    "JB Boda Reinsurance Brokers Private Limited",
    "JB Chemicals & Pharmaceuticals Limited",
    "JD Orgochem Limited",
    "Jeena & Company",
    "Jenburkt Pharmaceuticals Limited",
    "Jet Air  Private Limited",
    "Jet Airways India Limited",
    "Jewelex India  Private Limited",
    "Jindal Iron & Steel Company Limited",
    "JM Baxi & Company",
    "JM Financial Limited",
    "JM Financial Services Private Limited",
    "Jones Lang Lasalle Meghraj Property Consultants  Private Limited",
    "JP Morgan Asset Management India Private Limited",
    "JSW Energy Limited",
    "JSW Steel Limited",
    "JTB Travels Private Limited",
    "Juhu Beach Resorts Limited",
    "Juniper Hotels Private Limited",
    "Just Dial  Private Limited",
    "Jyothy Laboratories Limited",
    "Jyoti Structures Limited",
    "K Raheja Constructions  Private Limited",
    "K Raheja Corp",
    "Kabra Extrusion Technik Limited",
    "Kaira Can Company Limited",
    "Kama Schachter Jewellery Private Limited",
    "Kamat Hotels India Limited",
    "Kanji Shivji and Company",
    "Kankei Relationship Marketing Services Private Limited",
    "Kansai Nerolac Paints Limited",
    "Kasyap Sweetners Limited",
    "KB Bhabha Hospital",
    "KEC International Limited",
    "Kesar Enterprises Limited",
    "Kesari Tours  Private Limited",
    "Kewal Kiran Clothing Limited",
    "KGK Enterprises",
    "Khandelwal Laboratories  Private Limited",
    "King Edward Memorial Hospital and Seth Gordhandas Sunderdas Medical College",
    "Kiran Gems  Private Limited",
    "Kisan Irrigation Limited",
    "Kisan Mouldings Limited",
    "K-Lifestyle & Industries Limited",
    "KnowledgeWorks Global Limited",
    "Kobian Electronics India Private Limited",
    "Kohinoor Tele Video  Private Limited",
    "Kopran Limited",
    "Kores India Limited",
    "Kotak Mahindra Asset Management Company Limited",
    "Kotak Mahindra Bank Limited",
    "Kotak Mahindra Old Mutual Life Insurance Limited",
    "Kotak Mahindra Prime Limited",
    "Kotak Mahindra Securities Limited",
    "Kotak Securities Limited",
    "Kothari Creations Private Limited",
    "KPMG",
    "KPMG India  Private Limited",
    "Kris Flexipacks  Private Limited",
    "Krishna Knitwear Technology Limited",
    "Kuoni Travel India  Private Limited",
    "L&T Finance Limited",
    "L&T-Case Equipments Limited",
    "Lafarge India  Private Limited",
    "Lalji Mulji Transport Company",
    "Lans Metals Private Limited",
    "Larsen & Toubro Infotech Limited",
    "Larsen & Toubro Limited",
    "Lauren Information Technologies Private Limited",
    "Lawkim Limited",
    "Lawrence & Mayo India Private Limited",
    "Legrand India Private Limited",
    "Lehman Brothers Services India  Private Limited",
    "Liberty Oil Mills Limited",
    "LIC Housing Finance Limited",
    "LIC Mutual Fund Asset Management Company Limited",
    "Life Insurance Corporation of India",
    "Liladhar Pasoo Forwarders Private Limited",
    "Lilavati Hospital and Research Centre",
    "Lipi Data Systems Limited",
    "LKP Securities Limited",
    "Lloyds Finance Limited",
    "Lloyds Metals & Engineers Limited",
    "Lloyds Steel Industries Limited",
    "Lloyds TSB Global Services  Private Limited",
    "Lodha Builders  Private Limited",
    "Lokmanya Tilak Municipal General Hospital",
    "Loop Mobile India Limited",
    "L'Oreal India Private Limited",
    "Lowe Lintas India Private Limited",
    "Lupin Limited",
    "Macleods Pharmaceuticals Limited",
    "Maersk Global Service Centres India  Private Limited",
    "Maersk India  Private Limited",
    "Maersk Logistics India  Private Limited",
    "Maerskline India Private Limited",
    "Mafatlal Industries Limited",
    "Magna Publishing Company Limited",
    "Mahanagar Gas Limited",
    "Maharashtra State Electricity Distribution Company Limited",
    "Maharashtra State Electricity Transmission Company Limited",
    "Maharashtra State Power Generation Limited",
    "Mahendra Brothers Exports  Private Limited",
    "Mahimtura Consultants Private Limited",
    "Mahindra & Mahindra Financial Services Limited",
    "Mahindra & Mahindra Limited",
    "Mahindra Forgings Limited",
    "Mahindra Steel Service Centre Limited",
    "Majestic Software Limited",
    "Man Industries India Limited",
    "Mandhana Industries Limited",
    "Maneesh Pharmaceuticals Limited",
    "Manikgarh Cement",
    "Manugraph India Limited",
    "Marathon Nextgen Realty Limited",
    "Marathon Realty Private Limited",
    "Marico Limited",
    "Marksans Pharma Limited",
    "Marriott Hotels India  Private Limited",
    "Mars Restaurants  Private Limited",
    "Maruti Suzuki India Limited",
    "Mass Tech Controls Private Limited",
    "Mastek Limited",
    "Master Marine Services  Private Limited",
    "Mavi Industries Limited",
    "Maxwell Industries Limited",
    "Mazagon Dock Limited",
    "Medley Laboratories  Private Limited",
    "Medusind Solutions India Private Limited",
    "Meher Container Terminals  Private Limited",
    "Merchant Shipping Services Private Limited",
    "Merck Specialities Private Limited",
    "Metro Polymers Private Limited",
    "Metro Shoes Limited",
    "MF Global-Sify Securities India Private Limited",
    "Miel E-Security Private Limited",
    "Miltons Private Limited",
    "Minar International Limited",
    "Mindshare India  Private Limited",
    "Mirc Electronics Limited",
    "Mittal Ceratiles Private Limited",
    "MJ Patel India Limited",
    "MK Fashions",
    "Modern Petrofils",
    "Modern Syntex India Limited",
    "Modern Terry Towels Limited",
    "Monsanto Enterprises Limited",
    "Monsanto Holdings Private Limited",
    "Morarjee Textiles Limited",
    "Motilal Oswal Securities Limited",
    "Mott MacDonald  Private Limited",
    "Mott Macdonald Consultants India  Private Limited",
    "Mrf Limited",
    "MSC Agency India  Private Limited",
    "Mudra Communications Private Limited",
    "Mudra Lifestyle Limited",
    "Mukand Engineers Limited",
    "Mukat Fibres and Fabrics Limited",
    "Multi Commodity Exchange of India Limited",
    "Multi Screen Media Private Limited",
    "Mumbai International Airport  Private Limited",
    "Mumbai Kamgar Madhyavarti Grahak Sahakari Sanstha Limited",
    "Mysore Petro Chemicals Limited",
    "Narangs International Hotels  Private Limited",
    "National Aviation Company of India Limited",
    "National Securities Depository Limited",
    "National Sports Club of India",
    "National Stock Exchange of India Limited",
    "Navi Mumbai SEZ Private Limited",
    "Navin Fluorine International Limited",
    "Navinon Limited",
    "Navneet Publications India Limited",
    "NCR Corporation India Private Limited",
    "NDTV Media Limited",
    "Neelikon Food Dyes & Chemicals Limited",
    "Neon Laboratories Limited",
    "Nestle India Limited",
    "Networth Stock Broking Limited",
    "New City of Bombay Manufacturing Company Mill",
    "Next Retail India Limited",
    "Nhava Sheva International Container Terminal Private Limited",
    "Nhpc Limited",
    "Nilkamal Limited",
    "Nippon Yusen Kabushiki Kaisha Shipmanagement",
    "Nitco Limited",
    "Nmdc Limited",
    "NMIMS University",
    "Novalux Limited",
    "Novartis India Limited",
    "NRB Bearings Limited",
    "NRC Limited",
    "NSE Infotech Services Limited",
    "Ntpc Limited",
    "Nuclear Power Corporation of India Limited",
    "Ogilvy & Mather Private Limited",
    "Oil And Natural Gas Corporation Limited",
    "Oil India Limited",
    "Omnitech Infosolutions Limited",
    "Onward Technologies Limited",
    "Oracle Financial Services Software Limited",
    "Oricon Enterprises Limited",
    "Orion International Support Services  Private Limited",
    "Orix Auto Infrastructure Services Limited",
    "Osource India Private Limited",
    "Otis Elevator Company India Limited",
    "Packaging Warehouse Limited",
    "Pamac Finserve  Private Limited",
    "Pam-Glatt Pharma Technologies  Private Limited",
    "Pam-Pac Machines Private Limited",
    "Pangea3 Legal Database Systems Private Limited",
    "Pantaloon Retail India Limited",
    "Parasrampuria Industries Limited",
    "Parekh Marketing Limited",
    "Parle Agro Private Limited",
    "Parle Biscuits  Private Limited",
    "Parle Bisleri  Private Limited",
    "Parle International  Private Limited",
    "Parle Products  Private Limited",
    "Patel Engineering Limited",
    "Patel Integrated Logistics Limited",
    "Patel On-Board Couriers",
    "Patni Computer Systems Limited",
    "PBA Infrastructure Limited",
    "PCS Technology Limited",
    "PD Hinduja National Hospital & Medical Research Centre",
    "Pest Control India Private Limited",
    "Petron Engineering Construction Limited",
    "Petronet Lng Limited",
    "Pfizer Limited",
    "Pfizer Products India Private Limited",
    "Phonosonic India  Private Limited",
    "Pidilite Industries Limited",
    "Piem Hotels Limited",
    "Pioneer Embroideries Limited",
    "Piramal Enterprises Limited",
    "Piramal Healthcare Limited",
    "Poddar Pigments Limited",
    "Poddar Tyres Limited",
    "Polycab Wires Private Limited",
    "Power Finance Corporation Limited",
    "Power Grid Corporation Of India Limited",
    "Powerica Limited",
    "Prakash Air Freight  Private Limited",
    "Prana Studios Private Limited",
    "Pranavaditya Spinning Mills Limited",
    "Pratibha Industries Limited",
    "Precision Bearings Private Limited",
    "Precision Fasteners Limited",
    "Precision Rubber Industries Private Limited",
    "Prime Focus Limited",
    "Prince Pipes and Fittings  Private Limited",
    "Princeware International Private Limited",
    "Principal L N Welingkar Institute of Management Development & Research",
    "Procter & Gamble Home Products Limited",
    "Procter & Gamble Hygiene & Health Care Limited",
    "Procter & Gamble Hygiene and Health Care Limited",
    "Prothious Engineering Services Private Limited",
    "Provogue India Limited",
    "Prudential Process Management Services India  Private Limited",
    "PSL Limited",
    "Pudumjee Pulp & Paper Mills Limited",
    "Punjab National Bank",
    "PVN Plastics Industries",
    "Quinnox Consultancy Services Limited",
    "Quintiles Data Processing Centre India Private Limited",
    "Raj Oil Mills Limited",
    "Raj Petroleum Products Limited",
    "Rajendra Synthetics Private Limited",
    "Rajesh Garments Private Limited",
    "Rajshree Polyfil Limited",
    "RAK Ceramics India Private Limited",
    "Rallis India Limited",
    "Raptakos, Brett & Company Limited",
    "Rashtriya Chemicals & Fertilizers Limited",
    "Rashtriya Metal Industries Limited",
    "Raychem R P G Limited",
    "RBS Business Services  Private Limited",
    "Rediffusion-Y&R Private Limited",
    "Reliance Capital Asset Management Limited",
    "Reliance Capital Limited",
    "Reliance General Insurance Company Limited",
    "Reliance Industries Limited",
    "Reliance Infrastructure Limited",
    "Reliance Life Insurance Company Limited",
    "Reliance Logistics Private Limited",
    "Remsons Industries Limited",
    "Renaissance Jewellery Limited",
    "Repro India Limited",
    "Reuters India  Private Limited",
    "Rexcel Pharmaceuticals Limited",
    "Riya Travels and Tours India Private Limited",
    "RMC Readymix India Private Limited",
    "Rolta India Limited",
    "Rosy Blue India Private Limited",
    "Royal Star Jewellery Limited",
    "Royal Western India Turf Club Limited",
    "RPG Cables Limited",
    "RPG Enterprises Limited",
    "RR Kabel Limited",
    "RSM Advisory Services Private Limited",
    "Rural Electrification Corporation Limited",
    "S Kumars Nationwide Limited",
    "S Vinodkumar Diamonds Private Limited",
    "Sabero Organics Gujarat Limited",
    "Saf Yeast Company Private Limited",
    "Sahara Hospitality Limited",
    "Sahara One Media & Entertainment Limited",
    "Sai Service & Agency Bombay Private Limited",
    "Saint-Gobain Gyproc India Limited",
    "Sandu Brothers Private Limited",
    "Sanghavi Exports International  Private Limited",
    "Sanghavi Jewel Private Limited",
    "Sanghi Organization",
    "Sanjay Maintenance Services  Private Limited",
    "Satkaran Textiles Private Limited",
    "Saurashtra Cement Limited",
    "Savani Transport Private Limited",
    "Savita Oil Technologies Limited",
    "Savita Polymers Limited",
    "SBI Capital Markets Limited",
    "SBI Life Insurance Company Limited",
    "Schindler India Private Limited",
    "Schrader Duncan Limited",
    "SD Fine-Chem Limited",
    "SEAMEC Limited",
    "Sezal Glass Limited",
    "Shah Paper Mills Limited",
    "Shah Pulp & Paper Mills Limited",
    "Shalimar Paints Limited",
    "Shapoorji Pallonji & Company Limited",
    "Sharekhan Limited",
    "Shetron Limited",
    "Shirdi Industries Limited",
    "Shirt Company India Limited",
    "Shoppers Stop Limited",
    "Shree Cement Limited",
    "Shrenuj & Company Limited",
    "Shreya Life Sciences  Private Limited",
    "Shreyas Shipping & Logistics Limited",
    "Shri Meenakshi Food Products  Private Limited",
    "SI Group India Limited",
    "Siddhartha Super Spinning Mills Limited",
    "Siemens Limited",
    "Simplex Realty Limited",
    "Singapore Airlines Limited",
    "Sir Harkisandas Narottamdas Hospital & Research Centre",
    "Sitel India Limited",
    "Sitel Operating Corporation India Limited",
    "Siyaram Silk Mills Limited",
    "SK International",
    "SKF India Limited",
    "SKS Ispat & Power Limited",
    "Sky Industries Limited",
    "Skygourmet Catering  Private Limited",
    "Skypak Service Specialists Limited",
    "SL Raheja Hospital & Diabetic Research Centre",
    "SNDT Womens University",
    "Sodexo Food Solutions India  Private Limited",
    "Sodexo Pass Services India  Private Limited",
    "Solvay Pharma India Limited",
    "Sonal Garments India  Private Limited",
    "SOTC Kuoni Travel India Limited",
    "SPA Pharmaceuticals Limited",
    "Spanco Limited",
    "Spartan Engineering Industries Private Limited",
    "Speciality Restaurants  Private Limited",
    "Sriman Petrochemicals Limited",
    "Standard Chartered Finance Limited",
    "Standard Chartered-STCI Capital Markets Limited",
    "Star India  Private Limited",
    "State Bank Of India",
    "State Street Syntel Services  Private Limited",
    "State Transport Co-operative Bank Limited",
    "Steel Authority Of India Limited",
    "Sterling & Wilson  Private Limited",
    "Stock Holding Corporation of India Limited",
    "Stream International Services  Private Limited",
    "Stup Consultants  Private Limited",
    "Suashish Diamonds Limited",
    "Sun N Sand Hotel Limited",
    "Sun Pharma Advanced Research Company Limited",
    "Sun Pharmaceutical Industries Limited",
    "Super Religare Laboratories Limited",
    "Supreme Infrastructure India Limited",
    "Supreme Petrochem Limited",
    "Supreme Treves Private Limited",
    "Surat Goods Transport Private Limited",
    "Suresh Brothers",
    "Surstyle Jewellery Private Limited",
    "Sushil Finance Consultants Limited",
    "Sushil Financial Services Private Limited",
    "Syngenta Agro India Private Limited",
    "Syntel International  Private Limited",
    "Syntel Limited",
    "Systematic Steel Industries Limited",
    "Systematix Shares & Stocks India Limited",
    "TajSATS Air Catering Limited",
    "Tam Media Research Private Limited",
    "Taparia Tools Limited",
    "Tara Ultimo  Private Limited",
    "Tata A I G General Insurance Company Limited",
    "Tata A I G Life Insurance Company Limited",
    "Tata Capital Limited",
    "Tata Chemicals Limited",
    "Tata Communications Limited",
    "Tata Consultancy Services Limited",
    "Tata Consulting Engineers Limited",
    "Tata Finance Limited",
    "Tata Industries Limited",
    "Tata Interactive Systems Limited",
    "Tata International Limited",
    "Tata Memorial Hospital",
    "Tata Motors Limited",
    "Tata Power Broadband Company Limited",
    "Tata Sky Limited",
    "Tata Steel Limited",
    "Tata Steel Limited-Wires Division",
    "Tata Teleservices Limited",
    "TCS e-Serve Limited",
    "Tech Mahindra Limited",
    "Tech Pacific India Limited",
    "Technocraft Industries India Limited",
    "TechProcess Solutions Limited",
    "Tecnimont ICB  Private Limited",
    "Teknic Controlgear Private Limited",
    "Texport Syndicate India Limited",
    "The B D Petit Parsee General Hospital",
    "The Bombay Burmah Trading Corporation Limited",
    "The Bombay Dyeing & Manufacturing Company Limited",
    "The Indian Hotels Company Limited",
    "The Indian Hume Pipe Company Limited",
    "The Indian Smelting and Refining Company Limited",
    "The Leela Kempinski, Mumbai",
    "The Leela Palace Kempinski, Bangalore",
    "The Maharashtra Agro-Industries Development Corporation Limited",
    "The Maharashtra State Co-operative Housing Finance Corporation Limited",
    "The Municipal Co-operative Bank Limited",
    "The New India Assurance Company Limited",
    "The Professional Couriers Private Limited",
    "The Shamrao Vithal Co-operative Bank Limited",
    "The Shipping Corporation of India Limited",
    "The Supreme Industries Limited",
    "The Taj Mahal Palace & Tower Hotel  Private Limited",
    "The Tata Power Company Limited",
    "The Tinplate Company of India Limited",
    "The United Provinces Sugar Company Limited",
    "Themis Medicare Limited",
    "Thomas Cook India Limited",
    "TickerPlant Limited",
    "Time Technoplast Limited",
    "Times Global Broadcasting Company Limited",
    "Titan Company Limited",
    "Tops Detective and Security Services Limited",
    "Tops Security Limited",
    "Torrent Pharmaceuticals Limited",
    "Toshniwal Instruments India Private Limited",
    "Total Fina Elf India Limited",
    "Total Logistics India  Private Limited",
    "Total Shipping & Logistics Private Limited",
    "Total Solutions Facility Management  Private Limited",
    "Toyo Engineering India Limited",
    "Trade Wings Tours Limited",
    "Transasia Bio-Medicals Limited",
    "Transocean Limited",
    "Transworld Shipping Services India Private Limited",
    "Travel Corporation India Limited",
    "Travelpack Marketing & Leisure Services India Limited",
    "Trent Limited",
    "Tricom India Limited",
    "Tricom Information & Technology Limited",
    "Tricom Infotech Solutions Limited",
    "Trident Hotels",
    "Trig Guardforce Limited",
    "Trimax IT Infrastructure & Services Limited",
    "TUV India Private Limited",
    "Twilight Litaka Pharma Limited",
    "UCB India Private Limited",
    "Ugam Solutions Private Limited",
    "UHDE India Limited",
    "Ultratech Cement Limited",
    "Uni Deritend Limited",
    "Unichem Laboratories Limited",
    "Uni-Design Jewellery Private Limited",
    "Unilever Research India Limited",
    "Unimark Remedies Limited",
    "Uniphos Enterprises Limited",
    "Unique Industrial Handlers Private Limited",
    "United Shippers Limited",
    "United Spirits Limited",
    "Unity Infraprojects Limited",
    "Universal Medicare Private Limited",
    "University of Mumbai",
    "Upaasi Investment & Finance Private Limited",
    "Upl Limited",
    "US Consulate General, Mumbai",
    "Usha Garments Manufacturing Company Private Limited",
    "USV Limited",
    "Uttam Galva Steels Limited",
    "Vadinar Oil Terminal Limited",
    "Vadinar Power Company Limited",
    "Vaidya Sane Ayurved Laboratory Private Limited",
    "Varun Industries Limited",
    "Vedanta Limited",
    "Venus Jewel",
    "Venus Wire Industries Private Limited",
    "VFS India  Private Limited",
    "VHB Life Science Limited",
    "Viacom 18 Media Private Limited",
    "Vichare Courier Services  Private Limited",
    "Vidyut Metallics  Private Limited",
    "Vijay Sales",
    "Vijayjyot Seats  Private Limited",
    "Vinyl Chemicals India Limited",
    "VIP Industries Limited",
    "Vodafone Essar Limited",
    "Voltas Limited",
    "V-Trans India Limited",
    "VVF Limited",
    "Waaree Instruments Limited",
    "Walchandnagar Industries Limited",
    "Wardex Pharmaceuticals Private Limited",
    "Watson Pharma Private Limited",
    "Weizmann Limited",
    "Welspun Corp Limited",
    "Welspun India Limited",
    "Welspun Syntex Limited",
    "Welspun Terry Towels Limited",
    "Welspun Trading Limited",
    "Western Telecom Projects",
    "Willis Processing Services India  Private Limited",
    "Wilson Sandhu Logistics India Limited",
    "Wimco Limited",
    "Wipro Limited",
    "Wipro Technology Services Limited",
    "WMI Cranes Limited",
    "WNS Global Services  Private Limited",
    "Wockhardt Hospitals Limited",
    "Wockhardt Limited",
    "Worldwide Media Private Limited",
    "Writer Corporation Limited",
    "Writer Information Management Services Private Limited",
    "Wyeth Limited",
    "Yash Raj Films Private Limited",
    "Yes Bank Limited",
    "YOU Telecom India  Private Limited",
    "Zandu Realty Limited",
    "ZCL Chemicals Limited",
    "Zee Entertainment Enterprises Limited",
    "Zenith Computers Limited",
    "Zenith Infotech Limited",
    "Zenta  Private Limited",
    "Zenta Technologies  Private Limited",
    "Zero Octa Selective Sourcing India Private Limited",
    "Zodiac Clothing Company Limited",
    "Zuventus Healthcare Limited",
    "Aarti Drugs Limited",
    "Aarti Industries Limited",
    "Abb India Limited",
    "Abbott India Limited",
    "ABC Bearings Limited",
    "ABG Shipyard Limited",
    "AC Nielsen ORG-MARG  Private Limited",
    "AC Nielsen Research Services  Private Limited",
    "ACC Concrete Limited",
    "ACC Limited",
    "Accenture India  Private Limited",
    "ACC-Nihon Castings Limited",
    "Adani Ports And Special Economic Zone Limited",
    "Aditya Birla Management Corporation Limited",
    "Aditya Birla Nuvo Limited",
    "Aditya Birla Retail Limited",
    "Admiral Shipping Limited",
    "Ador Welding Limited",
    "Advance Power Display Systems Limited",
    "Aegis Limited",
    "Aegon Asset Management Company Private Limited",
    "AEGON Religare Life Insurance Company Limited",
    "AF Ferguson & Company",
    "Afcons Infrastructure Limited",
    "Agility Logistics  Private Limited",
    "Agio Pharmaceuticals Limited",
    "Aglowmed Limited",
    "AGS Infotech Private Limited",
    "Airline Financial Support Services India Private Limited",
    "Ajanta Pharma Limited",
    "Ajmera Housing Corporation",
    "Ajmera Realty & Infra India Limited",
    "AK Capital Services Limited",
    "Akasha Syncotex Limited",
    "Al Kabeer Exports Private Limited",
    "Albatross Shipping Limited",
    "ALC India Private Limited",
    "Alkem Laboratories Limited",
    "Allana Oil Mills Limited",
    "Allcargo Global Logistics Limited",
    "Alok Industries Limited",
    "Alpha Data Processing  Private Limited",
    "Amadeus Biotech & Pharmaceuticals",
    "Ambassador Sky Chef",
    "Ambuja Cements Limited",
    "Amforge Industries Limited",
    "Amol Paper Mills Private Limited",
    "Anand Rathi Financial Services Limited",
    "Anchor Daewoo Industries Limited",
    "Anchor Electricals & Electronics  Private Limited",
    "Anchor Health & Beauty Care Private Limited",
    "Andromeda Marketing  Private Limited",
    "Angel Broking Limited",
    "Angel Capital & Debt Market Limited",
    "Angel Commodities Broking  Private Limited",
    "Angel Shares & Stock Brokers Private Limited",
    "Ankur Drugs & Pharma Limited",
    "APL Agencies India Private Limited",
    "Aptech Limited",
    "Aqua Logistics Limited",
    "Aramex India Private Limited",
    "Arch Pharmalabs Limited",
    "Aries Agro Limited",
    "Aristo Pharmaceuticals  Private Limited",
    "Aristo Realty Developers Limited",
    "Aristocrat Marketing Limited",
    "Artek Surfin Chemicals Limited",
    "Artemis Biotech",
    "Ashapura Claytech Limited",
    "Ashapura Minechem Limited",
    "Ashika Sarees Limited",
    "Ashok Leyland Limited",
    "Ashok Piramal Management Corporation Limited",
    "Ashrit Holdings Limited",
    "Asia Motor Works Limited",
    "Asian Paints Limited",
    "Asian Star Company Limited",
    "Asianet Satellite Communications Limited",
    "Asit C Mehta Financial Services Limited",
    "Asit C Mehta Investment Intermediates Limited",
    "ASK Investment Managers Private Limited",
    "Associated Cables Private Limited",
    "Associated Capsules  Private Limited",
    "Astral Glass Private Limited",
    "Atlantic Shipping Private Limited",
    "Atos Origin India  Private Limited",
    "Aurionpro Solutions Limited",
    "Aurobindo Pharma Limited",
    "Automatic Electric Limited",
    "Automotive Manufacturers  Private Limited",
    "Aventis Pharma Limited",
    "Avenue Supermarts Private Limited",
    "AVS Ventures  Private Limited",
    "Axis Bank Limited",
    "Axis Risk Consulting Services Private Limited",
    "B Braun Medical India Private Limited",
    "Bajaj Auto Limited",
    "Bajaj Electricals Limited",
    "Bajaj Finance Limited",
    "Bajaj Finserv Limited",
    "Balkrishna Industries Limited",
    "Balkrishna Tyres",
    "Balsara Home Products Limited",
    "Balsara Hygiene Products Limited",
    "Bang Overseas Limited",
    "Bank Of Baroda",
    "Banswara Syntex Limited",
    "Barclays Securities India Private Limited",
    "Baroda Rayon Corporation Limited",
    "Baron International Limited",
    "BASF India Limited",
    "BASF Styrenics Private Limited",
    "Bat Enterprise Limited",
    "Bates Enterprises  Private Limited",
    "Batliboi Environmental Engineering Limited",
    "Batliboi Limited",
    "Bayer CropScience Limited",
    "BD&P Hotels India Private Limited",
    "Bechtel Enterprises India Private Limited",
    "Bennett, Coleman & Company Limited",
    "Berger Paints India Limited",
    "Bessar Diamonds  Private Limited",
    "Best IT World India  Private Limited",
    "BG India Energy Private Limited",
    "Bhansali Engineering Polymers Limited",
    "Bharat Bijlee Limited",
]
